language: python
python:
  - "3.6"
script: skip

jobs:
  include:
    - stage: generate documentations
      python:
        - "3.6"
      branches:
        only:
          - master
      install:
        - pip install sphinx sphinx-rtd-theme nbsphinx
      #  - pip install .
      script:
        - cd docs; make html
      deploy:
        provider: pages
        local_dir: docs/_build/html
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master